// UI concepts only. Audio/storage/network engines are intentionally not implied.
pub struct Concept {
    pub name: &'static str, pub category: &'static str, pub title: &'static str,
    pub subtitle: &'static str, pub bg: u32, pub ink: u32, pub accent: u32,
    pub secondary: u32, pub labels: [&'static str; 6], pub hint: &'static str, pub kind: i32,
}
pub const CONCEPTS: &[Concept] = &[
    Concept { name: "Morph", category: "SPECTRAL / SOUND GENOME", title: "Between two worlds", subtitle: "SOURCE A  →  TRANSFORMATION  →  SOURCE B", bg: 0x101e24, ink: 0xeaf3ec, accent: 0x9fe7c3, secondary: 0xf8b489, labels: ["Blend", "Spectral shape", "Pitch lock", "Transient", "Noise", "Dynamics"], hint: "XY field blends the two source profiles.", kind: 0 },
    Concept { name: "Orbit", category: "GENERATIVE / POLYRHYTHM", title: "A little solar system", subtitle: "CROSSINGS BECOME NOTES", bg: 0x15162b, ink: 0xeeedfb, accent: 0xbaa6ff, secondary: 0xf3c477, labels: ["Tempo", "Eccentricity", "Gravity", "Orbit speed", "Probability", "Swing"], hint: "Pads enable orbiting trigger points.", kind: 1 },
    Concept { name: "Fracture", category: "BUFFER / GLITCH LAB", title: "Beautifully broken", subtitle: "SLICE · REVERSE · REPEAT", bg: 0x201525, ink: 0xfff0ed, accent: 0xfb87b1, secondary: 0xa5e8ed, labels: ["Slice size", "Repeat", "Reverse", "Pitch", "Scatter", "Probability"], hint: "Pads select slices; Variation reshuffles.", kind: 2 },
    Concept { name: "Ghosts", category: "LOOP / DECAY", title: "Nothing disappears", subtitle: "FOUR GENERATIONS / ONE MEMORY", bg: 0x122024, ink: 0xe6efee, accent: 0x9ccecb, secondary: 0xc8b9e8, labels: ["Decay", "Drift", "Feedback", "Filter", "Reverse", "Wet"], hint: "Pads bring individual loop layers forward.", kind: 3 },
    Concept { name: "Swarm", category: "SYNTHESIS / POPULATION", title: "A living instrument", subtitle: "COHESION ↔ MUTATION", bg: 0x172019, ink: 0xedf2d9, accent: 0xd2eb8b, secondary: 0xeea777, labels: ["Voices", "Cohesion", "Pitch spread", "Attraction", "Mutation", "Density"], hint: "XY steers the population attraction point.", kind: 4 },
    Concept { name: "Mutant", category: "SYNTHESIS / PATCH BREEDER", title: "Keep the unexpected", subtitle: "TWO PARENTS / A NEW GENERATION", bg: 0x221827, ink: 0xf2eafa, accent: 0xc8a4f7, secondary: 0xeea6b2, labels: ["Inheritance", "Mutation", "Diversity", "Pitch", "Timbre", "Envelope"], hint: "Variation breeds a new visual generation.", kind: 5 },
    Concept { name: "Constellation", category: "HARMONY / PITCH SPACE", title: "Find a new harmony", subtitle: "SELECTABLE PITCH MAP / ROOT & VOICING", bg: 0x111d2b, ink: 0xe9f0f7, accent: 0x91c8f1, secondary: 0xf1c69e, labels: ["Root", "Spread", "Inversion", "Voice leading", "Tension", "Density"], hint: "Pads enable notes in the harmonic map.", kind: 6 },
    Concept { name: "Tape Machine", category: "STUDIO / MULTIHEAD TAPE", title: "Time, with texture", subtitle: "FOUR HEADS / ONE CONTINUOUS LOOP", bg: 0xe9e1cc, ink: 0x302f28, accent: 0x98602f, secondary: 0x437a71, labels: ["Speed", "Head offset", "Feedback", "Wow", "Flutter", "Saturation"], hint: "Pads arm heads; Variation changes splices.", kind: 7 },
    Concept { name: "Dream", category: "COMPOSITION / STATE MACHINE", title: "Let the story unfold", subtitle: "CALM → TENSION → CHAOS → RELEASE", bg: 0x171a2a, ink: 0xeeeafa, accent: 0xc0b0ef, secondary: 0xf2b89c, labels: ["Tempo", "Dwell", "Transition", "Complexity", "Tension", "Chance"], hint: "Pads choose a state; Motion previews transitions.", kind: 8 },
    Concept { name: "Portal", category: "SYSTEM / AUDIO ROUTING", title: "Make a connection", subtitle: "INSTRUMENTS · EFFECTS · MODULATION", bg: 0x111f24, ink: 0xe4eff1, accent: 0x80d9cc, secondary: 0xa9b7ef, labels: ["Source", "Destination", "Send", "Feedback", "Mod depth", "Output"], hint: "Pads toggle patch nodes in the routing study.", kind: 9 },
    Concept { name: "Reference", category: "LIBRARY / HIGH FIDELITY", title: "The space between", subtitle: "DEMO ALBUM / EIGHT TRACKS", bg: 0xeae4d5, ink: 0x283434, accent: 0x347c76, secondary: 0xb96547, labels: ["Track", "Position", "Volume", "Replay gain", "Queue", "Repeat"], hint: "A player layout study; no media is loaded.", kind: 10 },
    Concept { name: "Field", category: "CAPTURE / FIELD RECORDER", title: "Catch the moment", subtitle: "STEREO / PRE-RECORD BUFFER", bg: 0x14211e, ink: 0xe8efe1, accent: 0xbfe091, secondary: 0xf2b37f, labels: ["Gain", "Pre-roll", "Limiter", "Low cut", "Marker", "Monitor"], hint: "Meters are preview motion, not live input.", kind: 11 },
    Concept { name: "Sample Hunter", category: "CAPTURE / SAMPLE LIBRARY", title: "Turn places into instruments", subtitle: "TRIM → NAME → TAG → SEND", bg: 0x242018, ink: 0xf5ecdc, accent: 0xf0bc70, secondary: 0x99c5a4, labels: ["Start", "End", "Normalize", "Pitch", "Threshold", "Destination"], hint: "XY sets trim bounds in the sample study.", kind: 12 },
    Concept { name: "Studio", category: "RECORD / EIGHT TRACK", title: "A studio that travels", subtitle: "EIGHT TRACKS / ONE SESSION", bg: 0x16202a, ink: 0xe7eef6, accent: 0x9ebee5, secondary: 0xe4ad8e, labels: ["Track", "Position", "Level", "Pan", "Mute", "Solo"], hint: "Pads arm tracks; Variation previews a new take.", kind: 13 },
    Concept { name: "Scope", category: "MEASURE / AUDIO LAB", title: "See what you hear", subtitle: "SCOPE · SPECTRUM · STEREO", bg: 0x101f22, ink: 0xe3f0e9, accent: 0x78d6c4, secondary: 0xeec77f, labels: ["Timebase", "Gain", "Trigger", "Frequency", "Window", "Mode"], hint: "Signal generator visualization; no measurement input.", kind: 14 },
    Concept { name: "Vinyl", category: "LIBRARY / RECORD COLLECTION", title: "Browse by feeling", subtitle: "DEMO COLLECTION / 12 RECORDS", bg: 0x241c22, ink: 0xf3e8de, accent: 0xdca5b5, secondary: 0xd6c083, labels: ["Album", "Artist", "Year", "Sort", "Artwork", "Queue"], hint: "Artwork is original geometric demo art.", kind: 15 },
    Concept { name: "Practice", category: "LEARN / MUSICIAN COMPANION", title: "One phrase at a time", subtitle: "LOOP A–B / KEEP THE KEY", bg: 0xe6e8de, ink: 0x273734, accent: 0x387d6c, secondary: 0xac684a, labels: ["Tempo", "Loop start", "Loop end", "Pitch", "Click", "Balance"], hint: "Pads choose loop points; Motion previews the count.", kind: 16 },
    Concept { name: "Radio", category: "LISTEN / EXPLORATION", title: "Signals from elsewhere", subtitle: "STATION STUDY / NOT CONNECTED", bg: 0x161d2b, ink: 0xecedf6, accent: 0x94b1ed, secondary: 0xdf9fbd, labels: ["Station", "Tune", "Buffer", "Quality", "Record", "Volume"], hint: "Station labels are examples; no network connection.", kind: 17 },
    Concept { name: "Master", category: "FINISH / REFERENCE", title: "Listen in perspective", subtitle: "MIX A / REFERENCE B", bg: 0x1d1c27, ink: 0xecebf5, accent: 0xb9b1e6, secondary: 0xe4c287, labels: ["Reference", "Match", "Low shelf", "Presence", "Width", "Ceiling"], hint: "Comparison meters use a labeled demo signal.", kind: 18 },
    Concept { name: "Memories", category: "ARCHIVE / SONIC JOURNAL", title: "A life, in sound", subtitle: "DEMO TIMELINE / PERSONAL SOUND ATLAS", bg: 0xe8e0cf, ink: 0x3d3932, accent: 0x8a6347, secondary: 0x5d8276, labels: ["Entry", "Timeline", "Tag", "Favorite", "Playback", "Collection"], hint: "Journal entries are examples, not saved recordings.", kind: 19 },
];
