#!/usr/bin/env python3
"""Writes `sketch.cpp` and `prototypes.h` for an Arduino-sketch firmware: the .ino files
as one translation unit, the way the Arduino build joins them -- the main sketch's
headers first, then generated prototypes, the main sketch, then the rest alphabetically.

    tools/oc_sketch.py vendor/o_c_hemi o_c_REV.ino
"""
import glob, os, re, subprocess, sys

variant, main = sys.argv[1], sys.argv[2]
fw = os.path.join(variant, 'fw')
inos = sorted(os.path.basename(f) for f in glob.glob(os.path.join(fw, '*.ino')))
# Applets (HEM_*) first when present: the Hemisphere app's table names their functions,
# which the Arduino build's prototypes would have covered.
others = sorted((f for f in inos if f != main), key=lambda f: (not f.startswith('HEM_'), f))
text = open(os.path.join(fw, main)).read()
headers = [m.group(1) for m in re.finditer(r'^#include\s+<([^>]+)>', text, re.M)] 
local = [m.group(1) for m in re.finditer(r'^#include\s+"([^"]+)"', text, re.M)]
# Applets lean on what the app file includes; hoist those includes ahead of them.
for extra in sys.argv[3:]:
    if extra.endswith('.h'):
        local.append(extra)
        continue
    for m in re.finditer(r'^#include\s+"([^"]+)"', open(os.path.join(fw, extra)).read(), re.M):
        if m.group(1) not in local:
            local.append(m.group(1))
protos = subprocess.run([sys.executable, os.path.join(os.path.dirname(__file__), '..', 'vendor', 'o_c', 'tools', 'oc_prototypes.py'), fw], capture_output=True, text=True, check=True).stdout
open(os.path.join(variant, 'prototypes.h'), 'w').write(protos)
out = ['// The firmware is an Arduino sketch: its .ino files are concatenated into one',
       "// translation unit (main sketch first, with the prototypes the Arduino build adds).",
       "// Generated by tools/oc_sketch.py.", '#include <Arduino.h>']
out += [f'#include <{h}>' for h in headers if h != 'Arduino.h']
out += [f'#include "fw/{h}"' for h in local]
out += ['', '#include "prototypes.h"', f'#include "fw/{main}"']
out += [f'#include "fw/{f}"' for f in others]
open(os.path.join(variant, 'sketch.cpp'), 'w').write('\n'.join(out) + '\n')
print(len(inos), 'sketch files;', protos.count('\n'), 'prototypes')
