//! The shared transport: one tempo and one beat position that every
//! sequencer, looper and arpeggiator can follow, so pressing play in
//! Session also starts Skins' pattern and the Looper's loops, in time.
//!
//! How it stays sample-locked without any app talking to another: the
//! mix engine (`audio::MixBus::process`) calls `end_block` once after
//! every processor has rendered. So within a block every app reads the
//! *same* snapshot -- the beat at the block's first sample, and how
//! many beats one sample is -- and works out per-sample positions from
//! it. Two apps following the clock therefore fire their downbeats on
//! the very same sample, whatever order the engine runs them in.
//!
//! Start / stop / tempo changes from the UI thread are *requests*,
//! applied at the next block boundary, so no block ever sees half a
//! start (one app running, the next not).
//!
//! External sync: MIDI clock in (24 pulses per quarter note, plus
//! Start/Continue/Stop and Song Position Pointer) can drive it. The beat
//! still advances smoothly per sample at the tempo measured from the
//! pulses, and is pulled toward the pulse count each block, so a
//! drifting or jittery master is followed without the steps stuttering.
//! MIDI clock out is generated by `midi_devices.rs` from `beat_now()`.

use crate::util::AtomicF32;
use std::sync::atomic::{AtomicBool, AtomicU64, AtomicU8, Ordering};
use std::sync::Arc;
#[cfg(not(test))]
use std::sync::OnceLock;
use std::time::Instant;

pub const MIN_BPM: f32 = 30.0;
pub const MAX_BPM: f32 = 300.0;
/// MIDI clock's resolution.
pub const PPQN: f64 = 24.0;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Source {
    Internal,
    MidiIn,
}

const REQ_NONE: u8 = 0;
const REQ_START: u8 = 1;
const REQ_STOP: u8 = 2;
const REQ_CONTINUE: u8 = 3;

/// What one block sees.
#[derive(Clone, Copy, Debug)]
pub struct Snap {
    /// Beat (quarter notes since start) at this block's first sample.
    pub beat: f64,
    pub bpm: f32,
    pub running: bool,
    /// Bumped every time the transport (re)starts, so a follower can
    /// tell a restart from a loop of the same position.
    pub epoch: u64,
}

impl Snap {
    pub fn beats_per_sample(&self, sr: f32) -> f64 {
        self.bpm as f64 / 60.0 / sr.max(1.0) as f64
    }
    /// The beat at frame `i` of this block.
    pub fn beat_at(&self, i: usize, sr: f32) -> f64 {
        if self.running {
            self.beat + i as f64 * self.beats_per_sample(sr)
        } else {
            self.beat
        }
    }
}

pub struct Clock {
    tempo: AtomicF32,
    beat: AtomicU64,
    running: AtomicBool,
    epoch: AtomicU64,
    request: AtomicU8,
    source: AtomicU8,
    /// Beats per bar, for apps that quantise to the bar (4 = 4/4).
    pub beats_per_bar: AtomicU8,
    /// Whether `midi_devices` sends clock to every MIDI output.
    pub send_midi: AtomicBool,
    /// Raised by any app while it records against the clock (the
    /// Looper, Session), for Tempo's "click when recording".
    pub recording: AtomicBool,
    // -- external sync (written by the MIDI input thread) --
    ext_pulses: AtomicU64,
    ext_last_ns: AtomicU64,
    ext_tempo: AtomicF32,
    // -- for MIDI clock out: when the last block ended --
    block_ns: AtomicU64,
    origin: Instant,
}

impl Default for Clock {
    fn default() -> Self {
        Self::new()
    }
}

impl Clock {
    pub fn new() -> Self {
        Clock {
            tempo: AtomicF32::new(120.0),
            beat: AtomicU64::new(0f64.to_bits()),
            running: AtomicBool::new(false),
            epoch: AtomicU64::new(0),
            request: AtomicU8::new(REQ_NONE),
            source: AtomicU8::new(0),
            beats_per_bar: AtomicU8::new(4),
            send_midi: AtomicBool::new(false),
            recording: AtomicBool::new(false),
            ext_pulses: AtomicU64::new(0),
            ext_last_ns: AtomicU64::new(0),
            ext_tempo: AtomicF32::new(120.0),
            block_ns: AtomicU64::new(0),
            origin: Instant::now(),
        }
    }

    /// The one transport the device has. (Tests make their own with
    /// `Clock::new()` so parallel tests can't nudge each other.)
    #[cfg(not(test))]
    pub fn shared() -> Arc<Clock> {
        static SHARED: OnceLock<Arc<Clock>> = OnceLock::new();
        Arc::clone(SHARED.get_or_init(|| Arc::new(Clock::new())))
    }
    /// Under test every caller gets its own transport: tests run in
    /// parallel, and one test pressing play mustn't make another's app
    /// look like it started by itself.
    #[cfg(test)]
    pub fn shared() -> Arc<Clock> {
        Arc::new(Clock::new())
    }

    pub fn snap(&self) -> Snap {
        Snap {
            beat: f64::from_bits(self.beat.load(Ordering::Acquire)),
            bpm: self.bpm(),
            running: self.running.load(Ordering::Acquire),
            epoch: self.epoch.load(Ordering::Acquire),
        }
    }

    pub fn bpm(&self) -> f32 {
        match self.source() {
            Source::Internal => self.tempo.get(),
            Source::MidiIn => self.ext_tempo.get(),
        }
    }
    pub fn set_bpm(&self, bpm: f32) {
        self.tempo.set(bpm.clamp(MIN_BPM, MAX_BPM));
    }
    pub fn running(&self) -> bool {
        // A pending start already counts as running for the UI, so a
        // play button lights the moment it's pressed.
        match self.request.load(Ordering::Acquire) {
            REQ_START | REQ_CONTINUE => true,
            REQ_STOP => false,
            _ => self.running.load(Ordering::Acquire),
        }
    }
    pub fn source(&self) -> Source {
        if self.source.load(Ordering::Relaxed) == 1 {
            Source::MidiIn
        } else {
            Source::Internal
        }
    }
    pub fn set_source(&self, s: Source) {
        self.source.store(if s == Source::MidiIn { 1 } else { 0 }, Ordering::Relaxed);
    }
    pub fn bar_beats(&self) -> f64 {
        self.beats_per_bar.load(Ordering::Relaxed).max(1) as f64
    }

    /// Start from beat 0 (at the next block).
    pub fn start(&self) {
        self.request.store(REQ_START, Ordering::Release);
    }
    pub fn stop(&self) {
        self.request.store(REQ_STOP, Ordering::Release);
    }
    /// Carry on from where it stopped.
    pub fn resume(&self) {
        self.request.store(REQ_CONTINUE, Ordering::Release);
    }
    pub fn toggle(&self) {
        if self.running() {
            self.stop()
        } else {
            self.start()
        }
    }

    /// Called by the mix engine after every processor has rendered
    /// `frames` samples (and by tests in its place).
    pub fn end_block(&self, frames: usize, sr: f32) {
        let mut beat = f64::from_bits(self.beat.load(Ordering::Acquire));
        let mut running = self.running.load(Ordering::Acquire);
        if running {
            beat += frames as f64 * self.bpm() as f64 / 60.0 / sr.max(1.0) as f64;
            if self.source() == Source::MidiIn {
                // Pull toward where the pulses say we are; a tenth of the
                // error per block is smooth (no audible step jumps) yet
                // locks within a fraction of a second.
                let target = self.ext_pulses.load(Ordering::Acquire) as f64 / PPQN;
                // Never run more than one pulse ahead of the master: if
                // its pulses stop (cable pulled) we stop with them.
                beat += (target - beat) * 0.1;
                beat = beat.min(target + 1.0 / PPQN);
            }
        }
        match self.request.swap(REQ_NONE, Ordering::AcqRel) {
            REQ_START => {
                beat = 0.0;
                running = true;
                self.epoch.fetch_add(1, Ordering::AcqRel);
            }
            REQ_CONTINUE => {
                running = true;
                self.epoch.fetch_add(1, Ordering::AcqRel);
            }
            REQ_STOP => running = false,
            _ => {}
        }
        self.beat.store(beat.to_bits(), Ordering::Release);
        self.running.store(running, Ordering::Release);
        self.block_ns.store(self.origin.elapsed().as_nanos() as u64, Ordering::Release);
    }

    /// The beat right now on the wall clock: the last block's position
    /// plus the time since it ended. MIDI clock out uses this so its
    /// pulses aren't bunched up at block boundaries.
    pub fn beat_now(&self) -> f64 {
        let s = self.snap();
        if !s.running {
            return s.beat;
        }
        let since = self.origin.elapsed().as_nanos() as u64 - self.block_ns.load(Ordering::Acquire).min(self.origin.elapsed().as_nanos() as u64);
        // Cap the extrapolation at 50 ms: if audio stopped, so does time.
        s.beat + (since.min(50_000_000) as f64 / 1e9) * s.bpm as f64 / 60.0
    }

    /// One MIDI realtime / system-common message from any input port.
    /// Returns true if it was clock-related.
    pub fn midi_message(&self, msg: &[u8]) -> bool {
        let ext = self.source() == Source::MidiIn;
        match msg.first() {
            Some(0xF8) => {
                self.pulse_at(self.origin.elapsed().as_nanos() as u64);
                true
            }
            Some(0xFA) => {
                self.ext_pulses.store(0, Ordering::Release);
                if ext {
                    self.start();
                }
                true
            }
            Some(0xFB) => {
                if ext {
                    self.resume();
                }
                true
            }
            Some(0xFC) => {
                if ext {
                    self.stop();
                }
                true
            }
            Some(0xF2) if msg.len() >= 3 => {
                // Song Position Pointer: sixteenth notes since the start.
                let sixteenths = (msg[1] as u64 & 0x7F) | ((msg[2] as u64 & 0x7F) << 7);
                self.ext_pulses.store(sixteenths * 6, Ordering::Release);
                if ext {
                    self.beat.store((sixteenths as f64 / 4.0).to_bits(), Ordering::Release);
                }
                true
            }
            _ => false,
        }
    }

    /// A clock pulse arriving at `now` (ns on this clock's own timeline).
    fn pulse_at(&self, now: u64) {
        let last = self.ext_last_ns.swap(now, Ordering::AcqRel);
        if last > 0 && now > last {
            let dt = (now - last) as f64 / 1e9;
            // ignore gaps (stopped master) and impossibly fast pulses
            if dt < 0.1 && dt > 0.0005 {
                let bpm = (60.0 / (dt * PPQN)) as f32;
                let old = self.ext_tempo.get();
                // MIDI clock jitters by a millisecond or so a pulse;
                // average over about a beat.
                self.ext_tempo.set((old + (bpm - old) * 0.06).clamp(MIN_BPM, MAX_BPM));
            }
        }
        if self.running.load(Ordering::Acquire) {
            self.ext_pulses.fetch_add(1, Ordering::AcqRel);
        }
    }

    /// How a follower turns this block's snapshot into steps. Call once
    /// per frame with the frame's beat; returns the step to fire on this
    /// frame, if one starts here. `steps_per_beat` 4 = sixteenths.
    /// Swing delays every second step by `swing` of a step (0..0.4).
    pub fn step_at(beat: f64, steps_per_beat: u32, swing: f32) -> (u64, f64) {
        let s = beat.max(0.0) * steps_per_beat.max(1) as f64;
        let pair = (s / 2.0).floor();
        let frac = s / 2.0 - pair;
        let sw = swing.clamp(0.0, 0.4) as f64;
        let off = (1.0 + sw) / 2.0;
        let step = pair as u64 * 2 + if frac >= off { 1 } else { 0 };
        (step, frac)
    }
}

/// Turns a stream of per-frame beats into step triggers, firing each
/// step exactly once even if the frame lands mid-step (a restart) and
/// re-firing from 0 when the transport restarts.
#[derive(Default, Clone, Copy)]
pub struct StepFollower {
    next: u64,
    epoch: u64,
    primed: bool,
}

impl StepFollower {
    /// The step to fire at this frame, if any.
    pub fn poll(&mut self, snap: &Snap, beat: f64, steps_per_beat: u32, swing: f32) -> Option<u64> {
        if !snap.running {
            return None;
        }
        if !self.primed || snap.epoch != self.epoch {
            self.primed = true;
            self.epoch = snap.epoch;
            let (step, _) = Clock::step_at(beat, steps_per_beat, swing);
            // A restart lands exactly on a step: fire it. A late join
            // (an app opened mid-song) waits for the next step instead
            // of firing half a step late.
            let exact = (beat * steps_per_beat as f64).fract() < 1e-6;
            self.next = if exact { step } else { step + 1 };
        }
        let (step, _) = Clock::step_at(beat, steps_per_beat, swing);
        if step >= self.next {
            self.next = step + 1;
            Some(step)
        } else {
            None
        }
    }
    /// The next step this follower will fire.
    #[cfg(test)]
    pub fn upcoming(&self) -> u64 {
        self.next
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn requests_apply_at_the_block_boundary_and_time_advances_at_tempo() {
        let c = Clock::new();
        c.set_bpm(120.0);
        c.start();
        assert!(!c.snap().running, "a start mid-block mustn't be seen until the block ends");
        assert!(c.running(), "but the UI shows it at once");
        c.end_block(512, 48_000.0);
        let s = c.snap();
        assert!(s.running && s.beat == 0.0);
        for _ in 0..375 {
            c.end_block(256, 48_000.0);
        }
        // 96 000 samples at 120 bpm = 2 s = 4 beats
        assert!((c.snap().beat - 4.0).abs() < 1e-9, "{}", c.snap().beat);
        c.stop();
        c.end_block(256, 48_000.0);
        let b = c.snap().beat;
        c.end_block(256, 48_000.0);
        assert_eq!(c.snap().beat, b);
    }

    #[test]
    fn two_followers_fire_the_same_steps_on_the_same_samples() {
        let c = Clock::new();
        c.set_bpm(133.0);
        c.start();
        c.end_block(64, 48_000.0);
        let mut a = StepFollower::default();
        let mut b = StepFollower::default();
        let mut hits_a = vec![];
        let mut hits_b = vec![];
        let mut n = 0usize;
        for _ in 0..400 {
            let s = c.snap();
            for i in 0..128 {
                if let Some(st) = a.poll(&s, s.beat_at(i, 48_000.0), 4, 0.0) {
                    hits_a.push((st, n + i));
                }
            }
            for i in 0..128 {
                if let Some(st) = b.poll(&s, s.beat_at(i, 48_000.0), 4, 0.0) {
                    hits_b.push((st, n + i));
                }
            }
            n += 128;
            c.end_block(128, 48_000.0);
        }
        assert_eq!(hits_a, hits_b);
        assert_eq!(hits_a[0], (0, 0));
        // sixteenths at 133 bpm are 5413.5 samples apart
        let gap = (hits_a[8].1 - hits_a[0].1) as f64 / 8.0;
        assert!((gap - 48_000.0 * 60.0 / 133.0 / 4.0).abs() < 1.0, "{gap}");
        // consecutive, none skipped
        assert!(hits_a.iter().enumerate().all(|(i, h)| h.0 == i as u64));
    }

    #[test]
    fn swing_delays_the_off_beat_and_keeps_the_bar() {
        let c = Clock::new();
        c.set_bpm(120.0);
        c.start();
        c.end_block(1, 48_000.0);
        let mut f = StepFollower::default();
        let mut at = vec![];
        let mut n = 0;
        for _ in 0..200 {
            let s = c.snap();
            for i in 0..128 {
                if let Some(st) = f.poll(&s, s.beat_at(i, 48_000.0), 4, 0.25) {
                    at.push((st, n + i));
                }
            }
            n += 128;
            c.end_block(128, 48_000.0);
        }
        let step = 6000.0;
        let first = (at[1].1 - at[0].1) as f64;
        let second = (at[2].1 - at[1].1) as f64;
        assert!((first - step * 1.25).abs() < 2.0, "{first}");
        assert!((second - step * 0.75).abs() < 2.0, "{second}");
        assert!(((at[4].1 - at[0].1) as f64 - 4.0 * step).abs() < 2.0);
    }

    #[test]
    fn midi_clock_in_sets_the_tempo_and_position() {
        let c = Clock::new();
        c.set_source(Source::MidiIn);
        assert!(c.midi_message(&[0xFA]));
        c.end_block(64, 48_000.0);
        assert!(c.snap().running);
        // a master at 100 bpm: pulses every 25 ms
        let sr = 48_000.0;
        let per_pulse = 60.0 / 100.0 / 24.0;
        let mut t = 0.0;
        let mut sent = 0;
        for _ in 0..(sr as usize * 3 / 120) {
            let block_secs = 120.0 / sr;
            t += block_secs;
            while (sent as f64) * per_pulse <= t as f64 {
                // pulses at their true times, with a millisecond of jitter
                let jitter = if sent % 3 == 0 { 1e-3 } else { -0.5e-3 };
                c.pulse_at(((sent as f64 * per_pulse + 1.0 + jitter) * 1e9) as u64);
                sent += 1;
            }
            c.end_block(120, sr);
        }
        assert!((c.bpm() - 100.0).abs() < 1.0, "{}", c.bpm());
        let want = sent as f64 / 24.0;
        assert!((c.snap().beat - want).abs() < 0.1, "{} vs {want}", c.snap().beat);
        assert!(c.midi_message(&[0xFC]));
        c.end_block(64, sr);
        assert!(!c.snap().running);
        // SPP to bar 3 (32 sixteenths)
        c.midi_message(&[0xF2, 32, 0]);
        assert_eq!(c.snap().beat, 8.0);
    }

    #[test]
    fn a_follower_joining_mid_song_waits_for_the_next_step() {
        let c = Clock::new();
        c.start();
        c.end_block(1, 48_000.0);
        for _ in 0..10 {
            c.end_block(1000, 48_000.0);
        }
        let s = c.snap();
        let mut f = StepFollower::default();
        let got = f.poll(&s, s.beat_at(0, 48_000.0), 4, 0.0);
        assert_eq!(got, None);
        assert!(f.upcoming() > 0);
    }
}
